version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/esp_provisioning"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/esp_provisioning/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/esp_provisioning_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/esp_provisioning_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/esp_provisioning_ios"
    schedule:
      interval: "daily"