include: package:very_good_analysis/analysis_options.7.0.0.yaml

linter:
  rules:
    always_use_package_imports: false
    prefer_relative_imports: true
    public_member_api_docs: true
    lines_longer_than_80_chars: false

analyzer:
  exclude: [lib/**.g.dart, __generated__/**]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
