name: esp_provisioning
description: SpinDance Flutter federated plugin; wraps Espressif's native mobile provisioning libraries.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: esp_provisioning_android
      ios:
        default_package: esp_provisioning_ios

dependencies:
  esp_provisioning_android:
    path: ../esp_provisioning_android
  esp_provisioning_ios:
    path: ../esp_provisioning_ios
  esp_provisioning_platform_interface:
    path: ../esp_provisioning_platform_interface
  flutter:
    sdk: flutter
  permission_handler: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^5.1.0
