name: esp_provisioning_android

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/esp_provisioning_android.yaml"
      - "esp_provisioning_android/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/esp_provisioning_android.yaml"
      - "esp_provisioning_android/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.19.0
      working_directory: esp_provisioning_android
      format_line_length: "120"
      coverage_excludes: '**/*.g.dart **/*.freezed.dart'

